WebStudy/WebStudy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 设置命名空间
    url(r'^polls/',include('polls.urls',namespace="polls")),


]

WebStudy/polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
#     这个是请求详情id
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

WebStudy/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('时间')

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

WebStudy/polls/views.py
from django.http import HttpResponse
from .models import  Question
from django.template import loader
from django.shortcuts import get_object_or_404,render

# 直接返回读取出来的数据
# def index(request):
#     list = Question.objects.order_by('-pub_date')[:5]
#     output = ','.join([p.question_text for p in list])
#     return HttpResponse(output)



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    for i in latest_question_list:
        print(i.question_text)
    template = loader.get_template('index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
    # list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question_list':list,
    # }
    # return HttpResponse(template.render(context,request))

def detail(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'detail.html',{'question':question})
    return HttpResponse("这是你请求的question_id=%s"%question_id)

# 投票
def vote(request,question_id):
    return HttpResponse("这是你请求的question_id=%s" % question_id)
    return HttpResponse("投票成功了")

WebStudy/polls/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for choose in question.choice_set.all %}
    <li>{{ choose.choice_text }}</li>
{% endfor %}

<h1>{% csrf_token %}</h1>
{#form表单#}
<form action="{% url 'polls:vote' question.id %}" method="post" />
{% for choose in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choose.id }}">
    <label for="choice{{ forloop.counter }}">{{ choose.choice_text }}</label><br/>
{% endfor %}
<input type="submit" value="Vote" />
</body>
</html>

WebStudy/polls/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
{#        当前的是硬编码#}
{#        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#        #}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>